CREATE DATABASE PROJETO1;

USE PROJETO1;

CREATE TABLE CLIENTES(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    ESTADO CHAR(2),
    REGIAO VARCHAR(30),
    SEXO CHAR(1) NOT NULL
);

CREATE TABLE PLATAFORMA(
    IDPLATAFORMA INT PRIMARY KEY AUTO_INCREMENT,
    PLATAFORMA VARCHAR(20) NOT NULL
);

CREATE TABLE JOGOS(
    IDJOGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_JOGO VARCHAR(30) NOT NULL,
    DATA_LANCAMENTO DATE,
    PRECO_ALUGUEL INT NOT NULL, 
    QTD_DISPONIVEL INT NOT NULL
);

CREATE TABLE ALUGUEL(
    IDALUGUEL INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT,
    ID_JOGO INT,
    ID_PLATAFORMA INT,
    DATA_ALUGUEL DATE,
    NOTA INT
);

ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE);

ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_JOGO
FOREIGN KEY (ID_JOGO) REFERENCES JOGOS(IDJOGO);

ALTER TABLE ALUGUEL ADD CONSTRAINT FK_ALUGUEL_PLATAFORMA
FOREIGN KEY (ID_PLATAFORMA) REFERENCES PLATAFORMA(IDPLATAFORMA);


INSERT INTO CLIENTES VALUES(NULL, 'James Smith', '1985-07-12' ,'RJ', 'Rio De Janeiro', 'M');

INSERT INTO CLIENTES VALUES(NULL, 'Emma Johnson', '1992-02-28' ,'RS', 'Porto Alegre', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Benjamin Davis', '1978-11-03' ,'RS', 'Erechim', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Olivia Martinez', '1990-05-19','RS', 'Bento Goncalves', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'William Anderson', '1982-09-06','SP', 'São Paulo', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Ava Wilson', '1988-02-12 ','SP', 'Barueri', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'James Maclarenton', '1995-04-10' ,'SP', 'Rio Claro', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Alexander Thompson', '1989-12-30' ,'RJ', 'Rio de Janeiro', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Sophia White', '1987-08-25' ,'PR', 'Curitiba', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Michael Thomas', '1991-01-15','BA', 'Bahia', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Isabella Harris', '1984-06-21','RS', 'Gramado', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Matthew Martinez', '1977-10-08' ,'RJ', 'Rio de Janeiro', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Andrew Wilson', '1993-03-04 ','RS', 'Porto Alegre', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Harper Thompson', '1981-07-16' ,'RS', 'Porto Alegre', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Joshua Davis', '1988-09-10' ,'SP', 'São Paulo', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Amelia Thomas', '1976-07-22' ,'GO', 'Goias', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Ethan Johnson', ' 1999-02-19','ES', 'Espirito Santo', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Didico Maia', '2000-03-14' ,'RS', 'Pelotas', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Mia Wilson', '1986-06-09' ,'BA', 'Bahia', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Daniel White', '1990-11-26' ,'SP', 'Barueri', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Ava Taylor', '1983-04-16' ,'RJ', 'Rio de Janeiro', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Joseph Smith', '1980-08-01' ,'SP', 'São Paulo', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Harper Johnson', '1997-02-05' ,'RS', 'Porto Alegre', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'David Martinez', '1979-07-18' ,'ES', 'Espirito Santo', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Abigail Anderson', '1991-12-13' ,'ES', 'Espirito Santo', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Anderson Williams', '1985-09-03' ,'SP', 'Santos', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Mia Thompson', '1992-02-28', 'SP', 'Santos', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Alexander Davis', '1998-06-15','BA', 'Bahia', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Charlotte Brown', '1987-11-20','RS', 'Erechim', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Christopher Thomas', '1993-04-07','AC', 'Acre', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Olivia Taylor', '1984-10-23' ,'AL', 'Alagoas', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Noah Smith', '1981-02-12','GO', 'Goias', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Amelia Johnson', '1995-06-28' ,'MG', 'Minas Gerais', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Andrew Jones', '1978-12-01' ,'RS', 'Porto Alegre', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Emily Anderson', '1990-04-17' ,'MG', 'Minas Gerais', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Daniel Wilson', '1982-10-07' ,'RJ', 'Rio De Janeiro', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Tomas Mathias', '1989-07-03' ,'RJ', 'Rio de Janeiro', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Sophia Thompson', '1989-01-29','BA', 'Bahia', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'John Davis', ' 1994-07-14' ,'SP', 'Barueri', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Ava Brown', '1986-11-04' ,'AL', 'Alagoas', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Michael Tomas', '1991-04-22' ,'PR', 'Paraná', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Harper Taylor', '1983-10-12','RS', 'Porto Alegre', 'F');
INSERT INTO CLIENTES VALUES(NULL, 'Christopher Smith', ' 1980-02-07' ,'SP', 'São Paulo', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'John Tobias', '1979-12-09' ,'RJ', 'Rio de Janeiro', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Joshua Tim', '1995-12-12' ,'AL', 'Alagoas', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Smith Anderson', '1988-11-29' ,'GO', 'Goias', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'James Schimit', '1985-07-12' ,'BA', 'Bahia', 'M');
INSERT INTO CLIENTES VALUES(NULL, 'Andersen William', '1999-04-12' ,'RS', 'Pelotas', 'M');

INSERT INTO PLATAFORMA VALUES(NULL, "Playstation");
INSERT INTO PLATAFORMA VALUES(NULL, "Xbox");
INSERT INTO PLATAFORMA VALUES(NULL, "Pc");
INSERT INTO PLATAFORMA VALUES(NULL, "Nintendo Switch");

